# Bio/RNA/Treekin.pm
package Bio::RNA::Treekin;
our $VERSION = '0.01';

use 5.006;
use strict;
use warnings;

use IO::File::RecordStream;
use Bio::RNA::Treekin::PopulationDataRecord;
use Bio::RNA::Treekin::Record;
use Bio::RNA::Treekin::MultiRecord;

1;

__END__


=pod

=encoding UTF-8

=head1 NAME

Bio::RNA::Treekin - Classes for working with I<Treekin> output.

=head1 SYNOPSIS

    use Bio::RNA::Treekin;

    # Read multi-record file (records separated by single '&')
    my $treekin_records = Bio::RNA::Treekin::MultiRecord->new($treekin_file);

    # Iterate over single records.
    while (defined (my $next_treekin_record = $treekin_records->next)) {
        # Print current file name.
        print 'Treekin simulation for ', $next_treekin_record->rates_file, " \n";

        # Print population of minimum 42 at the end of the simulation
        my  $init_pop = $current_treekin_record->init_population;
        my $final_pop = $current_treekin_record->final_population;
        print 'min 42: ', $init_pop->of_min(42), ' => ',
              $final_pop->of_min(42), "\n";
    }

=head1 DESCRIPTION

This module provides auxiliary classes to parse, query and print the data
generated by the reaction kinetics simulation tool I<Treekin>, as well as
multi-simulations as generated by the I<BarMap> simulator.

=head1 CLASSES

=head1 METHODS OF C<Bio::RNA::Treekin::MultiRecord>

Reads multiple I<Treekin> records from a single file. The individual records
are separated by a line containing a single '&'.

=head2 new()

Constructor. Pass a file name or a file handle to the I<Treekin> multi-record
file.

=head2 next()

Returns the next I<Treekin> record, i.e. an object of type
C<Bio::RNA::Treekin::Record>.


=head1 METHODS OF C<Bio::RNA::Treekin::Record>


=head2 C<init_population()>

Get initial population data record, i.e. an object of type
C<Bio::RNA::PopulationDataRecord>. This is equal to the values given to
I<Treekin> via the C<--p0> command line arguments.

=head2 C<population_data_count()>

Number of population data records, i.e. number of time points for which
population data has been computed.

=head2 C<min_count()>

Number of states / minima in this simulation.

=head2 C<keep_mins(@mins)>

Keep only the population data for the selected minima, remove all other.
Will NOT rescale populations, so they may no longer sum up to 1.

Arguments:

=over

=item @mins

List of mins to keep. Will be sorted and uniq'ed (cf. C<splice()>).

=back

Returns the return value of C<splice()>.

=head2 C<splice_mins()>

Keep only the population data for the selected minima, remove all other.
May duplicate and re-order.

Arguments:

=over

=item @mins

List of mins to keep. Will be used as is.

=back

Returns itself.

=head2 C<max_pop_of_min()>

Get the maximal population for the given minimum over all time points.

=head2 C<final_population()>

Final population data record, i.e. the result of the simulation.

=head2 C<population()>

Get the i-th population data record (0-based indexing).

=head2 C<stringify()>

Converts the object back into a string. Also called by stringification
overloading in double quotes.

=head2 Querying header information

There are accessor methods for following attributes given in the header.

=over

=item *
rates_file

=item *

file_index

=item *

cmd

=item *

date

=item *

sequence

=item *

method

=item *

start_time

=item *

stop_time

=item *

temperature

=item *

basename

=item *

time_increment

=item *

degeneracy

=item *

absorbing_state

=item *

states_limit


=item *

info

=back


=head1 METHODS OF C<Bio::RNA::Treekin::PopulationDataRecord>

=head2 C<()>

TODO add


=head1 AUTHOR

Felix Kuehnl, C<< <felix@bioinf.uni-leipzig.de> >>


=head1 BUGS

Please report any bugs or feature requests to C<bug-bio-rna-treekin at
rt.cpan.org>, or through the web interface at
L<https://rt.cpan.org/NoAuth/ReportBug.html?Queue=Bio-RNA-Treekin>.  I will be
notified, and then you'll automatically be notified of progress on your bug as
I make changes.


=head1 SUPPORT

You can find documentation for this module with the perldoc command.

    perldoc Bio::RNA::Treekin


You can also look for information at:

=over 4

=item * RT: CPAN's request tracker (report bugs here)

L<https://rt.cpan.org/NoAuth/Bugs.html?Dist=Bio-RNA-Treekin>

=item * AnnoCPAN: Annotated CPAN documentation

L<http://annocpan.org/dist/Bio-RNA-Treekin>

=item * CPAN Ratings

L<https://cpanratings.perl.org/d/Bio-RNA-Treekin>

=item * Search CPAN

L<https://metacpan.org/release/Bio-RNA-Treekin>

=back


=head1 LICENSE AND COPYRIGHT

Copyright 2019 Felix Kuehnl.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see L<http://www.gnu.org/licenses/>.


=cut

# End of Bio::RNA::Treekin

